oraios/serena

src/serena/agent.py

This change adds the Serena version number to the server startup log message, making it easier to identify which version is running when reviewing logs.

Add Serena version to server startup logs

---

src/serena/agent.py

Turned out to be trivial... No need to change any interfaces, I just filter out everything afterwards. Since the scandir tool was also doing that, it's not even a performance hit

Don't list ignored files and dirs

---

CHANGELOG.md
src/serena/agent.py

* Tool description was incompatible with project change
* Returned result was not as useful as it could be (now added list of memories)

Fix CheckOnboardingPerformedTool

---

CHANGELOG.md
src/multilspy/language_server.py
src/multilspy/language_servers/eclipse_jdtls/eclipse_jdtls.py
src/multilspy/language_servers/gopls/gopls.py
src/multilspy/language_servers/jedi_language_server/jedi_server.py
src/multilspy/language_servers/omnisharp/omnisharp.py
src/multilspy/language_servers/pyright_language_server/pyright_server.py
src/multilspy/language_servers/rust_analyzer/rust_analyzer.py
src/multilspy/language_servers/solargraph/solargraph.py
src/multilspy/language_servers/typescript_language_server/typescript_language_server.py
src/serena/agent.py
src/serena/util/file_system.py

Fix handling of ignored paths in ListDirTool:
Do not limit results to files not ignored by the LanguageServer, but retain ignoring of ignored directories
Improve handling of ignored paths in LanguageServer:
* Improve method naming: 
* should_always_ignore -> is_ignored_dirname 
* should_ignore_path -> is_ignored_path
* Fix is_ignored_dirname (should_always_ignore) being applied to filenames
* Add option ignore_unsupported_files to is_ignored_path to improve versatility
Fixes #59

Fix handling of ignored paths

---

src/multilspy/language_servers/dart_language_server/runtime_dependencies.json

This is the same content of the [PR to multispy](https://github.com/microsoft/multilspy/pull/105) to add support to other platforms for Dart LSP.

Add missing dependencies to multilspy to run Dart LSP in Windows and MacOS

---

pyproject.toml
src/serena/mcp.py
test/serena/test_mcp.py
uv.lock

This PR enhances the MCP server by extracting parameter descriptions from Python docstrings - that would appear in the tools description - and passing them to the proper `description` field of each parameter. The change improves quality of tool documentation available to LLMs.
The PR includes test coverage to validate the parameter description extraction functionality. Tests ensure that docstrings in various formats are correctly parsed and that the parameter descriptions are properly integrated into MCP tools.
This enhancement will improve the parsing of the tools by LLMs and also the tool evaluating experience for users. Below is an example of the tool listing on RooCode before and after the change:
Before | After
:-------------------------:|:-------------------------:

Parse parameter descriptions from docstring into MCP tool

---

src/serena/agent.py

Fixes the following issue:
```
Traceback (most recent call last):
File "/Users/user/serena/.venv/bin/serena-mcp-server", line 10, in <module>
sys.exit(start_mcp_server())
^^^^^^^^^^^^^^^^^^
File "/Users/user/serena/.venv/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/user/serena/.venv/lib/python3.11/site-packages/click/core.py", line 1082, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/Users/user/serena/.venv/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/user/serena/.venv/lib/python3.11/site-packages/click/core.py", line 788, in invoke
return __callback(*args, **kwargs) …
```

fixup: add missing description to ListDir tool

---

src/multilspy/language_server.py

```
Error executing tool: 'relativePath'
Traceback (most recent call last):
File "/workspaces/serena/src/serena/agent.py", line 551, in apply_ex
result = apply_fn(**kwargs)
^^^^^^^^^^^^^^^^^^
File "/workspaces/serena/src/serena/agent.py", line 1247, in apply
matches = self.language_server.search_files_for_pattern(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspaces/serena/src/multilspy/language_server.py", line 2022, in search_files_for_pattern
).result(timeout=self.timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/coder/.local/share/uv/python/cpython-3.11.12-linux-x86_64-gnu/lib/python3.11/concurrent/futures/_base.py", line 456, in result
return self.__get_result()
^^^^^^^^^^^^^^^^^^^
File "/home/coder/.local/share/uv/python/cpython-3.11.12-linux-x86_64-gnu/lib/python3.11/con …
```

Add checks for 'location' and 'relativePath' in fix_relative_path function

---

pyproject.toml

I'm a little bit lazy. I won't want to have to first download serena just to use it.
With this change, you will be able to run:
```
uvx --from git+https://github.com/oraios/serena  -U serena-list-tools
```
(You can try it from my fork:  `uvx --from git+https://github.com/EricAtORS/serena  -U serena-list-tools`)
The `-U` is only needed  is to force uv/uvx to refresh and update the serena package. It's only needed because no one is managing the version number.
I did not update the readme as I think it's still premature to use it in this way.

support uvx run

---

src/serena/symbol.py

Hey, I added explicit utf-8 encoding to _edited_file() in symbol.py since it's been causing extensive problems. I believe it's been just overlooked, but if native encoding was intentional, be so kind to explain the reason :) #109

specified utf-8 encoding in symbol.py

---

src/multilspy/language_server.py
src/multilspy/language_servers/intelephense/initialize_params.json
src/multilspy/language_servers/intelephense/intelephense.py
src/multilspy/language_servers/intelephense/runtime_dependencies.json
src/multilspy/multilspy_config.py

Hi @MischaPanch and Team,
Sorry for the late update — I needed to add runtime dependencies for Intelephense. For context, I initially copied the setup from the TypeScript LSP and adapted it. It’s working well on my Mac.
The find_symbol and find_referencing_symbols features are also working. You can see some discussion here: [Claude conversation](https://claude.ai/share/7289d239-cb79-433b-a385-67c4e88274bc).
As mentioned in #59, I’m not confident in resolving deeper issues related to this LSP integration or the surrounding Python code. If anyone has more experience and can help improve or clean up the implementation, I’d really appreciate it.
Thanks!

Add PHP support with Intelephense LSP

---

src/multilspy/language_server.py
src/multilspy/multilspy_config.py
src/serena/agent.py
src/serena/util/file_system.py

1. Use all gitignore files in SerenaAgent, not just top level
2. Listing and file finding tools now can find all non-ignored files (previously they would only find code files)
3. Read and edit tools will raise an error on attempting to operate on an ignored file or a path outside the project root
Closes #137

Gitignore handling and read-edit tools - important fixes and improvments

---

.github/workflows/codespell.yml
.serena/memories/suggested_commands.md
CHANGELOG.md
lessons_learned.md
pyproject.toml
src/multilspy/lsp_protocol_handler/lsp_constants.py
src/multilspy/lsp_protocol_handler/lsp_types.py
src/multilspy/multilspy_logger.py
src/multilspy/multilspy_utils.py
src/serena/agent.py
src/serena/resources/config/modes/editing.yml
src/serena/resources/config/prompt_templates/system_prompt.yml
src/serena/symbol.py
test/serena/test_symbol.py

More about codespell: https://github.com/codespell-project/codespell .
I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.
CI workflow has 'permissions' set only to 'read' so also should be safe.

Add codespell support (config, workflow to detect/not fix) and make it fix some typos

---

scripts/demo_run_tools.py
src/serena/agent.py
src/serena/constants.py
src/serena/dashboard.py
src/serena/mcp.py
src/solidlsp/ls_handler.py

Use a thread pool with one worker (effectively a task queue for strictly sequential execution) in which we perform the language server startup and to which we issue tool executions with timeouts.
Resolves #183 
Resolves #184 
Resolves #201

Use a synchronized task queue for agent tasks and LS initialization

---

pyproject.toml

Just that. Uses `-n auto` in the test suite for max speed. Should halve test time on CI given that GH uses 2 cores in their runners. But it's mostly nicer for local testing

Add pytest-xdist for parallel tests

---

src/serena/agent.py

Very good, though could be more elegant and made a minor mistake in the order of conditionals.
Accepting, I pushed a minor fix in a follow-up commit
Tokens: 1,691,910
Serena Tool Stats:
Prompt (after initial instructions): same as in #318, here for completeness
When the serena mcp server is started in ide-assistant mode and a project is passed, we should:                                                                                                                         │
│                                                                                                                                                                                                                           │
│   1. check the excluded tools from the project.yml. If no project.yml exists, there are no …

Apply project-specific tool exclusions early, cc_serena

---

src/serena/project.py
src/solidlsp/language_servers/clangd_language_server.py
src/solidlsp/language_servers/clojure_lsp.py
src/solidlsp/language_servers/csharp_language_server.py
src/solidlsp/language_servers/dart_language_server.py
src/solidlsp/language_servers/eclipse_jdtls.py
src/solidlsp/language_servers/elixir_tools/elixir_tools.py
src/solidlsp/language_servers/gopls.py
src/solidlsp/language_servers/intelephense.py
src/solidlsp/language_servers/jedi_server.py
src/solidlsp/language_servers/kotlin_language_server.py
src/solidlsp/language_servers/omnisharp.py
src/solidlsp/language_servers/pyright_server.py
src/solidlsp/language_servers/rust_analyzer.py
src/solidlsp/language_servers/solargraph.py
src/solidlsp/language_servers/terraform_ls.py
src/solidlsp/language_servers/typescript_language_server.py
src/solidlsp/language_servers/vts_language_server.py
src/solidlsp/ls.py
test/conftest.py
test/solidlsp/csharp/test_csharp_basic.py

Tokens: 5,213,813
Prompts:
- I recently added the non-optional parameter solidlsp_settings to the init of SolidLanguageServer, the create method, and the ls_resources_dir method. All language server subclasses now need to be adjusted  accordingly to use solidlsp_settings. Do that. You can have a look at relevant memories in .serena/memories to understand the repo structure
- don't execute elixir tests, they hang

Refactoring solidlsp settings CC Vanilla

---

src/serena/resources/dashboard/dashboard.js

Escape special HTML characters in log messages to prevent XSS vulnerabilities and ensure proper display of code snippets containing HTML tags.

Fix: Add HTML escaping to dashboard log messages

---

docs/serena_on_chatgpt.md
scripts/demo_run_tools.py
src/serena/agent.py
src/serena/cli.py
src/serena/config/context_mode.py
src/serena/mcp.py
src/serena/resources/config/contexts/agent.yml
src/serena/resources/config/contexts/chatgpt.yml
src/serena/resources/config/contexts/context.template.yml
src/serena/resources/config/contexts/desktop-app.yml
src/serena/resources/config/contexts/ide-assistant.yml
src/serena/resources/config/modes/mode.template.yml
src/serena/tools/cmd_tools.py
src/serena/tools/config_tools.py
src/serena/tools/file_tools.py
src/serena/tools/memory_tools.py
src/serena/tools/symbol_tools.py
src/serena/tools/workflow_tools.py
src/solidlsp/language_servers/solargraph.py
test/serena/test_mcp.py

This basically works, but there are two restrictions
1. Chatgpt will accept a maximum of 30 tools, we have more.
2. Chatgpt only accepts short descriptions of tools, up to 300 chars. We have much longer ones
We can solve 1 easily by having a custom chatgpt context, but 2 is a problem. We could solve it by allowing tool description overrides in the context, something that we have discussed a while ago.
This feature is very sexy IMO and comes to us for free using mcpo. Especially witch GPT5 around the corner. It also allows people to use premium models for coding without more subscriptions.
@opcode81 pls have a look at the doc file (it's very short)
Rejected approaches:
- using mcpo as a library and adding a custom cli command to serena (not possible with mcpo)
- documenting sse mode. MCPO …

Connecting Serena to chatgpt

---

src/serena/resources/dashboard/dashboard.js

Addresses issue #388 by implementing auto-close functionality for dashboard tabs when the MCP server becomes unresponsive.
Found this minimal change can resolve the issue mentioned by users. Following @opcode81's suggestion (one of the 81 contributors), implemented the approach of detecting when server stops responding and automatically closing the tab.
Please review and accept if it is helpful\! Thanks.
Fixes #388

Auto-close dashboard tabs when server stops responding

---

.github/workflows/pytest.yml
pyproject.toml
test/resources/repos/ruby/test_repo/.solargraph.yml
test/resources/repos/ruby/test_repo/lib.rb
test/resources/repos/ruby/test_repo/main.rb
test/solidlsp/ruby/test_ruby_basic.py

This pull request adds initial support and tests for the Ruby language server integration. The main focus is on enabling and verifying Ruby language server functionality, including symbol detection and referencing in test repositories.
**Ruby language server integration:**
* Added `"ruby: language server running for Ruby"` marker to `pyproject.toml` to recognize Ruby language server status.
* Introduced a sample Ruby project in `test/resources/repos/ruby/test_repo/` with a `.solargraph.yml` configuration and a `main.rb` file containing example Ruby code for testing. [[1]](diffhunk://#diff-5f3ab12ac62a0089a91ede9c022a66a7cde1b9c14dd24bb75c859c03efe442f9R1-R3) [[2]](diffhunk://#diff-307747c41e30bc467f5acb170a9331e9192d75ac6cfa9f5d51303e9f9e67026eR1-R18)
**Testing and validation:**
* Added …

Add Ruby language test for language server integration

---

README.md

It seems that Swift was added in each of the following two PRs at different positions, so there was no conflict and both were merged, resulting in duplication.
- #401
- #437

Remove duplicate Swift

---

src/serena/symbol.py
src/solidlsp/ls.py
test/solidlsp/python/test_symbol_retrieval.py

... instead of creating new low-level data structures.
This enables uniform handling of required conversions in our higher-level Serena data structures
Fixes #432

Make LS overview calls return the full symbol information

---

src/serena/cli.py

The command was missing a call to `logging.configure` to actually configure logging and make the option have a visible effect.

fix: `--log-level` option for `serena index`

---

src/serena/tools/file_tools.py

Now when LLMs try to access non-existent paths, they get clear feedback about what went wrong and where they are in the filesystem.
Similar to fix in commit 8464f25 for CreateTextFileTool

Fix ListDirTool FileNotFoundError for non-existent directories

---

src/solidlsp/language_servers/csharp_language_server.py
src/solidlsp/language_servers/typescript_language_server.py
src/solidlsp/language_servers/vts_language_server.py
src/solidlsp/ls.py
test/solidlsp/csharp/test_csharp_basic.py

Now waiting only once instead of on each request, hopefully that's enough

Improve waiting logic for cross-file references to be ready

---

src/solidlsp/language_servers/nixd_ls.py
test/resources/repos/nix/test_repo/default.nix
test/serena/__snapshots__/test_symbol_editing.ambr
test/serena/test_symbol_editing.py
test/solidlsp/nix/test_nix_basic.py

This fixes the double semicolon issue in replace_symbol_body when replacing Nix attributes with content that includes semicolons.
Root cause: nixd provides expression-level ranges (excluding semicolons) but serena expects statement-level ranges (including semicolons).
Solution: Override request_document_symbols() in NixLanguageServer to detect and include trailing semicolons in symbol ranges.

Fix: Extend Nix symbol ranges to include trailing semicolons

---

src/solidlsp/language_servers/elixir_tools/elixir_tools.py

A small update to:
- add support for the OSX ARM64 version of ElixirLS
- upgrade ElixirLS to v0.23.4

Elixir / NextLS: Add support for the OSX_arm64 platform and update to release v0.23.4

---

src/solidlsp/language_servers/eclipse_jdtls.py

1. Upgrade Gradle version
- Default Gradle version is updated from 7.3.3 to 8.14.2.
- Gradle 7.x does not support Java 21 (class file major version 65), while Gradle 8.14.2 provides full compatibility.
2. Disable Gradle Wrapper
- Previously, the Gradle version depended on each project’s wrapper configuration.
- Older projects using outdated Gradle wrappers caused compilation errors with Java 21.
- By disabling the wrapper, Serena will consistently use the configured Gradle version (8.14.2) for all builds.
- Ensures Serena compiles projects correctly under Java 21.
- Prevents build failures caused by mismatched or outdated Gradle wrapper versions.

Upgrade gradle to 8.14.2 and disable gradle wrapper for java 21 compatibility
